name: CI

on: [push, pull_request]

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'
    - name: Build
      run: pwsh make.ps1
    - name: Package
      run: pwsh make.ps1 package
    - uses: actions/upload-artifact@v4
      with:
        name: packages-windows
        path: Package/Release/Packages

  build-ubuntu:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'
    - name: Build
      run: pwsh make.ps1
    - name: Package
      run: pwsh make.ps1 package
    - uses: actions/upload-artifact@v4
      with:
        name: packages-ubuntu
        path: Package/Release/Packages

  build-macos:
    name: Build (macOS)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'
    - name: Build
      run: pwsh make.ps1
    - name: Package
      run: pwsh make.ps1 package
    - uses: actions/upload-artifact@v4
      with:
        name: packages-macos
        path: Package/Release/Packages

  test-windows:
    name: Test (Windows)
    runs-on: windows-latest
    needs: build-windows
    steps:
    - uses: actions/checkout@v4
    - name: Test (net462)
      run: ./make.ps1 -frameworks net462 test-all
      shell: pwsh
    - name: Test (net8.0)
      run: ./make.ps1 -frameworks net8.0 test-all
      shell: pwsh
    - name: Test (net9.0)
      run: ./make.ps1 -frameworks net9.0 test-all
      shell: pwsh

  test-ubuntu:
    name: Test (Linux)
    runs-on: ubuntu-latest
    needs: build-ubuntu
    steps:
    - uses: actions/checkout@v4
    - name: Test (net462)
      run: ./make.ps1 -frameworks net462 test-all
      shell: pwsh
    - name: Test (net8.0)
      run: ./make.ps1 -frameworks net8.0 test-all
      shell: pwsh
    - name: Test (net9.0)
      run: ./make.ps1 -frameworks net9.0 test-all
      shell: pwsh

  test-macos:
    name: Test (macOS)
    runs-on: macos-latest
    needs: build-macos
    steps:
    - uses: actions/checkout@v4
    - name: Test (net462)
      run: ./make.ps1 -frameworks net462 test-all
      shell: pwsh
    - name: Test (net8.0)
      run: ./make.ps1 -frameworks net8.0 test-all
      shell: pwsh
    - name: Test (net9.0)
      run: ./make.ps1 -frameworks net9.0 test-all
      shell: pwsh
